services:
  backend:
    build: .
    ports:
      - "5148:5148"
    environment:
      - SCHEDULING_DATABASE_URL=postgresql://postgres:postgres@postgres_scheduling:5432/scheduling
    env_file:
      - .env
    networks:
      - my_shared_network
    volumes:
      - file-storage-data:/local_storage

networks:
  my_shared_network:
    external: true

volumes:
  file-storage-data:
